namespace FourthDown.Api.Models
{
    public class PlayByPlay
    {
        public int PlayId { get; set; }
        public int Week { get; set; }
        public string GameId { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string SeasonType { get; set; }
        public int? YardLine100 { get; set; }
        public int QuarterSecondsRemaining { get; set; }
        public int HalfSecondsRemaining { get; set; }
        public int GameSecondsRemaining { get; set; }
        public int? Drive { get; set; }
        public int Qtr { get; set; }
        public int? Down { get; set; }
        public string Desc { get; set; }
        public string PlayType { get; set; }
        public int YdsToGo { get; set; }
        public int? YardsNet { get; set; }
        public int? YardsGained { get; set; }
        public int? AirYards { get; set; }
        public int? YardsAfterCatch { get; set; }
        public int TotalHomeScore { get; set; }
        public int TotalAwayScore { get; set; }
        public int? ScoreDifferential { get; set; }
        public int? PosTeamScorePost { get; set; }
        public int? DefTeamScorePost { get; set; }
        public int? ScoreDifferentialPost { get; set; }
        public double? Ep { get; set; }
        public double? Epa { get; set; }
        public double TotalHomeEpa { get; set; }
        public double TotalAwayEpa { get; set; }
        public double TotalHomeRushEpa { get; set; }
        public double TotalAwayRushEpa { get; set; }
        public double TotalHomePassEpa { get; set; }
        public double TotalAwayPassEpa { get; set; }
        public double? AirEpa { get; set; }
        public double? YacEpa { get; set; }
        public double? CompAirEpa { get; set; }
        public double? CompYacEpa { get; set; }
        public double TotalHomeCompAirEpa { get; set; }
        public double TotalAwayCompAirEpa { get; set; }
        public double TotalHomeCompYacEpa { get; set; }
        public double TotalAwayCompYacEpa { get; set; }
        public double TotalHomeRawAirEpa { get; set; }
        public double TotalAwayRawAirEpa { get; set; }
        public double TotalHomeRawYacEpa { get; set; }
        public double TotalAwayRawYacEpa { get; set; }
        public double TotalHomeRushWpa { get; set; }
        public double TotalAwayRushWpa { get; set; }
        public double TotalHomePassWpa { get; set; }
        public double TotalAwayPassWpa { get; set; }
        public double? AirWpa { get; set; }
        public double? YacWpa { get; set; }
        public double? CompAirWpa { get; set; }
        public double? CompYacWpa { get; set; }
        public double TotalHomeCompAirWpa { get; set; }
        public double TotalAwayCompAirWpa { get; set; }
        public double TotalHomeCompYacWpa { get; set; }
        public double TotalAwayCompYacWpa { get; set; }
        public double TotalHomeRawAirWpa { get; set; }
        public double TotalAwayRawAirWpa { get; set; }
        public double TotalHomeRawYacWpa { get; set; }
        public double TotalAwayRawYacWpa { get; set; }
        public string SeriesResult { get; set; }
        public string PlayTypeNfl { get; set; }
        public int FixedDrive { get; set; }
        public string FixedDriveResult { get; set; }
        public string DriveRealStartTime { get; set; }
        public int? DrivePlayCount { get; set; }
        public string DriveTimeOfPossession { get; set; }
        public int? DriveFirstDowns { get; set; }
        public int? DriveInside20 { get; set; }
        public int? DriveEndedWithScore { get; set; }
        public int? DriveYardsPenalized { get; set; }
        public string DriveStartTransition { get; set; }
        public string DriveEndTransition { get; set; }
        public string DriveStartYardLine { get; set; }
        public string DriveEndYardLine { get; set; }
        public int? StartDrivePlayId { get; set; }
        public int? EndDrivePlayId { get; set; }
        public bool? IsSuccess { get; set; }
        public bool IsPass { get; set; }
        public bool IsRush { get; set; }
        public bool? IsFirstDown { get; set; }
        public bool IsAbortedPlay { get; set; }
        public bool Play { get; set; }
        public int Shotgun { get; set; }
        public int NoHuddle { get; set; }
        public int? QbDropBack { get; set; }
        public int QbKneel { get; set; }
        public int QbSpike { get; set; }
        public int QbScramble { get; set; }
        public string PasserName { get; set; }
        public string RusherName { get; set; }
        public string ReceiverName { get; set; }
        public string Name { get; set; }
        public double? CompletionProbability { get; set; }
        public double? CompletionProbabilityOverExpected { get; set; }
        public double? QbEpa { get; set; }
        public double? ExpectedYardsAfterCatchEpa { get; set; }
        public double? ExpectedYardsAfterCatchMeanYardage { get; set; }
        public int? ExpectedYardsAfterCatchMedianYardage { get; set; }
        public double? ExpectedYardsAfterCatchSuccess { get; set; }
        public double? ExpectedYardsAfterCatchFirstDown { get; set; }
    }
}