version: '3.4'

services:
  # api:
  #   image: api:latest
  #   environment:
  #     JAEGER_AGENT_HOST: tasks.jaeger
  #     JAEGER_AGENT_PORT: 6831
  #     JAEGER_SAMPLER_TYPE: const
  #     JAEGER_SAMPLER_PARAM: 1
  #     JAEGER_SERVICE_NAME: fourthdown-api
  #   ports:
  #   - 5000:5000
  #   networks: 
  #     - monitoring

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 9411:9411
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 19411:19411
    networks: 
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - 9090:9090
    networks: 
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=password1
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards/:/var/lib/grafana/dashboards
      - ./grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks: 
      - monitoring

networks: 
  monitoring:
    external:
      name: monitoring
