version: '3.4'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 9411:9411
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 19411:19411
    networks: 
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - 9090:9090
    networks: 
      - monitoring

  grafana:
    image: grafana/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=password1
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks: 
      - monitoring

networks: 
  monitoring:
    external:
      name: monitoring
