# See Prometheus configuration for more details
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 10s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'fourthdown-api-read-prometheus'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
        - 'tasks.api'
        type: 'A'
        port: 5000
