# See Prometheus configuration for more details
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 15s 
  scrape_timeout: 10s
  evaluation_interval: 15s

  external_labels:
    monitor: 'fourthdown-monitor'

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093

# rule_files:
#   - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'fourthdown-api'
    scrape_interval: 5s
    static_configs:
         - targets: ['host.docker.internal:5000']
