# See Prometheus configuration for more details
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 15s 
  scrape_timeout: 10s
  evaluation_interval: 15s

  external_labels:
    monitor: 'fourthdown-monitor'

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093

# rule_files:
#   - "first_rules.yml"

scrape_configs:
  - job_name: fourthdown-api  
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - api:5000
