# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Jaeger
    orgId: 2

# list of datasources to insert/update depending
# what's available in the database
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true

- name: Jaeger
  type: jaeger
  access: proxy
  orgId: 2
  url: http://jaeger:16686
  isDefault: false
  version: 1
  editable: true