version: '3.4'

services:
  api:
    image: api:latest
    environment:
      Telemetry__UseApplicationInsights: ${USE_APPLICATIONINSIGHTS-false}
      Telemetry__UseOpenTelemetry: ${USE_OPENTELEMETRY-true}
      Telemetry__ApplicationInsightsInstrumentationKey: ${AI_INSTRUMENTATIONKEY-}
      Telemetry__ApplicationInsightsForOpenTelemetryInstrumentationKey: ${AI_INSTRUMENTATIONKEY_OPENTELEMETRY-}
    ports:
    - 5000:5000
    networks: 
      - monitoring

networks: 
  monitoring:
    external:
      name: monitoring
